<a href="https://colab.research.google.com/github/chandBadal/AI_ML/blob/main/worksheet0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [38]:
# Task 1: Unit Conversion Program

def convert_units(conversion_type, value, from_unit, to_unit):
    """
    Converts a value from one unit to another.

    Parameters:
    conversion_type (str): Type of conversion ('length', 'weight', 'volume')
    value (float): Numeric value to convert
    from_unit (str): Original unit
    to_unit (str): Target unit

    Returns:
    float: Converted value
    """
    # Length conversions
    if conversion_type == "length":
        if from_unit == "m" and to_unit == "ft":
            return value * 3.28084
        elif from_unit == "ft" and to_unit == "m":
            return value / 3.28084
        else:
            raise ValueError("Unsupported length units. Use 'm' or 'ft'.")
    # Weight conversions
    elif conversion_type == "weight":
        if from_unit == "kg" and to_unit == "lbs":
            return value * 2.20462
        elif from_unit == "lbs" and to_unit == "kg":
            return value / 2.20462
        else:
            raise ValueError("Unsupported weight units. Use 'kg' or 'lbs'.")
    # Volume conversions
    elif conversion_type == "volume":
        if from_unit == "L" and to_unit == "gal":
            return value * 0.264172
        elif from_unit == "gal" and to_unit == "L":
            return value / 0.264172
        else:
            raise ValueError("Unsupported volume units. Use 'L' or 'gal'.")
    else:
        raise ValueError("Unsupported conversion type. Choose 'length', 'weight', or 'volume'.")

# Main program
def main():
    print("Welcome to the Unit Converter!")
    print("Conversion Types: length, weight, volume")
    try:
        conversion_type = input("Choose conversion type: ").strip().lower()
        value = float(input("Enter the value to convert: "))
        from_unit = input("Enter the original unit: ").strip().lower()
        to_unit = input("Enter the target unit: ").strip().lower()

        result = convert_units(conversion_type, value, from_unit, to_unit)
        print(f"{value} {from_unit} is equal to {result:.2f} {to_unit}")

    except ValueError as e:
        print("Error:", e)
    except Exception:
        print("Invalid input! Please try again with correct values.")

# Run the program
if __name__ == "__main__":
    main()

Welcome to the Unit Converter!
Conversion Types: length, weight, volume
Choose conversion type: length
Enter the value to convert: 20
Enter the original unit: m
Enter the target unit: ft
20.0 m is equal to 65.62 ft


In [39]:
def calculate_sum(numbers):
    """Returns the sum of a list of numbers."""
    return sum(numbers)

def calculate_average(numbers):
    """Returns the average of a list of numbers."""
    return sum(numbers)/len(numbers)

def find_max(numbers):
    """Returns the maximum number in a list."""
    return max(numbers)

def find_min(numbers):
    """Returns the minimum number in a list."""
    return min(numbers)

# User Interaction
try:
    operation = input("Choose operation (sum, average, max, min): ").lower()
    numbers = list(map(float, input("Enter numbers separated by spaces: ").split()))

    if not numbers:
        raise ValueError("List cannot be empty")

    if operation == "sum":
        print("Sum:", calculate_sum(numbers))
    elif operation == "average":
        print("Average:", calculate_average(numbers))
    elif operation == "max":
        print("Maximum:", find_max(numbers))
    elif operation == "min":
        print("Minimum:", find_min(numbers))
    else:
        print("Invalid operation")
except ValueError as e:
    print("Error:", e)

Choose operation (sum, average, max, min): sum
Enter numbers separated by spaces: 50 12 20 13
Sum: 95.0


In [40]:
# 4.2 Exercise on List Manipulation

def extract_every_other(lst):
    """
    Returns every other element from the list starting from the first.

    Parameters:
    lst (list): Input list

    Returns:
    list: New list with every other element
    """
    return lst[::2]

def get_sublist(lst, start, end):
    """
    Returns a sublist from start to end (inclusive).

    Parameters:
    lst (list): Input list
    start (int): Starting index
    end (int): Ending index

    Returns:
    list: Sublist from start to end
    """
    return lst[start:end+1]

def reverse_list(lst):
    """
    Returns the reversed list using slicing.

    Parameters:
    lst (list): Input list

    Returns:
    list: Reversed list
    """
    return lst[::-1]

def remove_first_last(lst):
    """
    Removes the first and last elements from a list.

    Parameters:
    lst (list): Input list

    Returns:
    list: List without first and last elements
    """
    return lst[1:-1]

def get_first_n(lst, n):
    """
    Returns the first n elements from a list.

    Parameters:
    lst (list): Input list
    n (int): Number of elements to return

    Returns:
    list: First n elements
    """
    return lst[:n]

def get_last_n(lst, n):
    """
    Returns the last n elements from a list.

    Parameters:
    lst (list): Input list
    n (int): Number of elements to return

    Returns:
    list: Last n elements
    """
    return lst[-n:]

def reverse_skip(lst):
    """
    Returns every second element starting from second-to-last, moving backward.

    Parameters:
    lst (list): Input list

    Returns:
    list: List of elements in reverse order with skipping
    """
    return lst[-2::-2]

# Example usage
example_list = [1, 2, 3, 4, 5, 6]

print("Original list:", example_list)
print("Every other element:", extract_every_other(example_list))
print("Sublist (2 to 4):", get_sublist(example_list, 2, 4))
print("Reversed list:", reverse_list(example_list))
print("Remove first and last:", remove_first_last(example_list))
print("First 3 elements:", get_first_n(example_list, 3))
print("Last 2 elements:", get_last_n(example_list, 2))
print("Reverse skip:", reverse_skip(example_list))

Original list: [1, 2, 3, 4, 5, 6]
Every other element: [1, 3, 5]
Sublist (2 to 4): [3, 4, 5]
Reversed list: [6, 5, 4, 3, 2, 1]
Remove first and last: [2, 3, 4, 5]
First 3 elements: [1, 2, 3]
Last 2 elements: [5, 6]
Reverse skip: [5, 3, 1]


In [41]:
# 4.3 Exercise on Nested List

def flatten(lst):
    """
    Flattens a nested list (1 level) into a single list.

    Parameters:
    lst (list): Nested list

    Returns:
    list: Flattened list
    """
    result = []
    for item in lst:
        if isinstance(item, list):
            result.extend(item)
        else:
            result.append(item)
    return result

def access_nested_element(lst, indices):
    """
    Accesses a nested element given a list of indices.

    Parameters:
    lst (list): Nested list
    indices (list): List of indices

    Returns:
    element: Element at the nested position
    """
    for idx in indices:
        lst = lst[idx]
    return lst

def sum_nested(lst):
    """
    Calculates the sum of all elements in a nested list (any depth).

    Parameters:
    lst (list): Nested list

    Returns:
    float: Sum of all elements
    """
    total = 0
    for item in lst:
        if isinstance(item, list):
            total += sum_nested(item)
        else:
            total += item
    return total

def remove_element(lst, elem):
    """
    Removes all occurrences of a specific element from a nested list.

    Parameters:
    lst (list): Nested list
    elem: Element to remove

    Returns:
    list: Nested list with element removed
    """
    result = []
    for item in lst:
        if isinstance(item, list):
            result.append(remove_element(item, elem))
        elif item != elem:
            result.append(item)
    return result

def find_max_nested(lst):
    """
    Finds the maximum element in a nested list (any depth).

    Parameters:
    lst (list): Nested list

    Returns:
    float: Maximum element
    """
    max_val = float('-inf')
    for item in lst:
        if isinstance(item, list):
            max_val = max(max_val, find_max_nested(item))
        else:
            max_val = max(max_val, item)
    return max_val

def count_occurrences(lst, elem):
    """
    Counts occurrences of a specific element in a nested list.

    Parameters:
    lst (list): Nested list
    elem: Element to count

    Returns:
    int: Number of occurrences
    """
    count = 0
    for item in lst:
        if isinstance(item, list):
            count += count_occurrences(item, elem)
        elif item == elem:
            count += 1
    return count

def deep_flatten(lst):
    """
    Flattens a deeply nested list into a single list (any depth).

    Parameters:
    lst (list): Nested list

    Returns:
    list: Flattened list
    """
    result = []
    for item in lst:
        if isinstance(item, list):
            result.extend(deep_flatten(item))
        else:
            result.append(item)
    return result

def average_nested(lst):
    """
    Calculates the average of all elements in a nested list.

    Parameters:
    lst (list): Nested list

    Returns:
    float: Average of elements
    """
    flat_list = deep_flatten(lst)
    return sum(flat_list) / len(flat_list)

# Example Usage
nested_list1 = [[1,2],[3,4],[5]]
nested_list2 = [[1,2],[3,[4,5]],6]
nested_list3 = [[1,2],[2,3],[2,4]]

print("Flatten:", flatten(nested_list1))
print("Access [1,2]:", access_nested_element([[1,2,3],[4,5,6],[7,8,9]],[1,2]))
print("Sum nested:", sum_nested(nested_list2))
print("Remove 2:", remove_element(nested_list3, 2))
print("Max nested:", find_max_nested(nested_list2))
print("Count 2:", count_occurrences(nested_list3, 2))
print("Deep flatten:", deep_flatten([[[1,2],[3,4]],[[5,6],[7,8]]]))
print("Average nested:", average_nested([[1,2],[3,4],[5,6]]))

Flatten: [1, 2, 3, 4, 5]
Access [1,2]: 6
Sum nested: 21
Remove 2: [[1], [3], [4]]
Max nested: 6
Count 2: 3
Deep flatten: [1, 2, 3, 4, 5, 6, 7, 8]
Average nested: 3.5


Basic Vector and Matrix Operation with Numpy.

In [42]:
import numpy as np

print("=== Problem 1: Array Creation ===")

# 1. Initialize an empty array with size 2x2
empty_array = np.empty((2,2))
print("Empty 2x2 array:\n", empty_array)

# 2. Initialize an all one array with size 4x2
ones_array = np.ones((4,2))
print("\nAll ones 4x2 array:\n", ones_array)

# 3. Array with given shape and fill value
filled_array = np.full((3,3), 7)  # example fill value 7
print("\nFilled 3x3 array with 7:\n", filled_array)

# 4. Array of zeros like a given array
zeros_like_array = np.zeros_like(filled_array)
print("\nZeros like filled_array:\n", zeros_like_array)

# 5. Array of ones like a given array
ones_like_array = np.ones_like(filled_array)
print("\nOnes like filled_array:\n", ones_like_array)

# 6. Convert list to numpy array
new_list = [1,2,3,4]
array_from_list = np.array(new_list)
print("\nArray from list:", array_from_list)


print("\n=== Problem 2: Array Manipulation ===")

# 1. Array values from 10 to 49
arr_10_49 = np.arange(10,50)
print("Array 10-49:", arr_10_49)

# 2. 3x3 matrix from 0 to 8
matrix_3x3 = np.arange(9).reshape(3,3)
print("\n3x3 Matrix:\n", matrix_3x3)

# 3. Identity 3x3
identity_matrix = np.eye(3)
print("\nIdentity 3x3:\n", identity_matrix)

# 4. Random array of size 30, mean
rand_arr_30 = np.random.random(30)
print("\nRandom array size 30, mean:", rand_arr_30.mean())

# 5. 10x10 random array, min & max
rand_10x10 = np.random.random((10,10))
print("\n10x10 Random array, min:", rand_10x10.min(), "max:", rand_10x10.max())

# 6. Zero array of size 10, replace 5th element
zero_10 = np.zeros(10)
zero_10[4] = 1
print("\nZero array with 5th element = 1:", zero_10)

# 7. Reverse array
arr = np.array([1,2,0,0,4,0])
print("\nReversed array:", arr[::-1])

# 8. 2D array with 1 on border, 0 inside
border_array = np.ones((5,5))
border_array[1:-1,1:-1] = 0
print("\n2D array with border 1, inside 0:\n", border_array)

# 9. 8x8 checkerboard
checkerboard = np.zeros((8,8),dtype=int)
checkerboard[1::2, ::2] = 1
checkerboard[::2,1::2] = 1
print("\n8x8 Checkerboard pattern:\n", checkerboard)


print("\n=== Problem 3: Array Operations ===")

x = np.array([[1,2],[3,5]])
y = np.array([[5,6],[7,8]])
v = np.array([9,10])
w = np.array([11,12])

# 1. Add
print("x + y:\n", x + y)

# 2. Subtract
print("x - y:\n", x - y)

# 3. Multiply by integer 3
print("x * 3:\n", x * 3)

# 4. Square of each element
print("x squared:\n", x**2)

# 5. Dot product
print("v.dot(w):", np.dot(v,w))
print("x.dot(v):", x.dot(v))
print("x.dot(y):\n", x.dot(y))

# 6. Concatenate
print("Concatenate x and y along row:\n", np.concatenate((x,y), axis=0))
print("Concatenate v and w along column:\n", np.concatenate((v,w)).reshape(-1,1))

# 7. Concatenate x and v -> Will raise error
try:
    print(np.concatenate((x,v)))
except Exception as e:
    print("Error concatenating x and v:", e)


print("\n=== Problem 4: Matrix Operations ===")

A = np.array([[3,4],[7,8]])
B = np.array([[5,3],[2,1]])

# 1. Prove A * A^-1 = I
A_inv = np.linalg.inv(A)
I = np.dot(A, A_inv)
print("A * A^-1 =\n", I)

# 2. Prove AB != BA
print("AB:\n", np.dot(A,B))
print("BA:\n", np.dot(B,A))

# 3. Prove (AB)^T = B^T A^T
AB_T = np.dot(A,B).T
B_TA_T = np.dot(B.T, A.T)
print("(AB)^T =\n", AB_T)
print("B^T A^T =\n", B_TA_T)
print("Equality check:", np.allclose(AB_T, B_TA_T))


# Solve system of linear equations
# 2x - 3y + z = -1
# x - y + 2z = -3
# 3x + y - z = 9

coeff_matrix = np.array([[2,-3,1],[1,-1,2],[3,1,-1]])
const_vector = np.array([-1,-3,9])

# Using np.linalg.solve
solution = np.linalg.solve(coeff_matrix, const_vector)
print("\nSolution of system [x, y, z]:", solution)

=== Problem 1: Array Creation ===
Empty 2x2 array:
 [[23. 51.]
 [13. 29.]]

All ones 4x2 array:
 [[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]

Filled 3x3 array with 7:
 [[7 7 7]
 [7 7 7]
 [7 7 7]]

Zeros like filled_array:
 [[0 0 0]
 [0 0 0]
 [0 0 0]]

Ones like filled_array:
 [[1 1 1]
 [1 1 1]
 [1 1 1]]

Array from list: [1 2 3 4]

=== Problem 2: Array Manipulation ===
Array 10-49: [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]

3x3 Matrix:
 [[0 1 2]
 [3 4 5]
 [6 7 8]]

Identity 3x3:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

Random array size 30, mean: 0.5352659411133549

10x10 Random array, min: 0.002234569071085546 max: 0.9880501251247351

Zero array with 5th element = 1: [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]

Reversed array: [0 4 0 0 2 1]

2D array with border 1, inside 0:
 [[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]

8x8 Checkerboard pattern:
 [[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 

Experiment: How Fast is Numpy?


In [43]:
import time

size = 1_000_000
list1 = list(range(size))
list2 = list(range(size))

# Python Lists Addition
start = time.time()
py_add = [list1[i]+list2[i] for i in range(size)]
end = time.time()
print("Python list addition time:", end-start, "seconds")

# NumPy Array Addition
arr1 = np.arange(size)
arr2 = np.arange(size)
start = time.time()
np_add = arr1 + arr2
end = time.time()
print("NumPy array addition time:", end-start, "seconds")


# Python Lists Multiplication
start = time.time()
py_mul = [list1[i]*list2[i] for i in range(size)]
end = time.time()
print("Python list multiplication time:", end-start, "seconds")

# NumPy Array Multiplication
start = time.time()
np_mul = arr1 * arr2
end = time.time()
print("NumPy array multiplication time:", end-start, "seconds")


# Dot product Python lists
start = time.time()
py_dot = sum([list1[i]*list2[i] for i in range(size)])
end = time.time()
print("Python list dot product time:", end-start, "seconds")

# Dot product NumPy arrays
start = time.time()
np_dot = np.dot(arr1,arr2)
end = time.time()
print("NumPy array dot product time:", end-start, "seconds")


# Matrix multiplication 1000x1000
size_m = 1000
# Python lists
mat1 = [[i+j for j in range(size_m)] for i in range(size_m)]
mat2 = [[i-j for j in range(size_m)] for i in range(size_m)]
start = time.time()
py_result = [[sum(mat1[i][k]*mat2[k][j] for k in range(size_m)) for j in range(size_m)] for i in range(size_m)]
end = time.time()
print("Python lists matrix multiplication time:", end-start, "seconds")

# NumPy arrays
np_mat1 = np.arange(size_m*size_m).reshape(size_m,size_m)
np_mat2 = np.arange(size_m*size_m).reshape(size_m,size_m)
start = time.time()
np_result = np.dot(np_mat1,np_mat2)
end = time.time()
print("NumPy arrays matrix multiplication time:", end-start, "seconds")

Python list addition time: 0.07480430603027344 seconds
NumPy array addition time: 0.0018401145935058594 seconds
Python list multiplication time: 0.07451295852661133 seconds
NumPy array multiplication time: 0.002568483352661133 seconds
Python list dot product time: 0.07765388488769531 seconds
NumPy array dot product time: 0.0009441375732421875 seconds
Python lists matrix multiplication time: 136.25880336761475 seconds
NumPy arrays matrix multiplication time: 0.9006054401397705 seconds
